# Generated by Django 4.2 on 2025-05-08 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('money_flow', '0003_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
