# Generated by Django 4.2 on 2025-05-08 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('money_flow', '0004_alter_note_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
